"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CANCEL_ON_NEW_PROMPT_CONFIG = exports.TTS_DEFAULT_OPTIONS_CONFIG = exports.TTS_ENGINE_CONFIG = exports.ASR_ENGINE_CONFIG = exports.BARGE_IN_CONFIG = exports.SPEECH_IO_INPUT_STATES_ID = exports.SPEECH_IO_INPUT_ENGINE_ID = exports.SPEECH_IO_INPUT_ID = exports.SPEECH_IO_STATES_ID = exports.SPEECH_IO_ENGINE_ID = exports.SPEECH_IO_MANAGER_ID = exports.READ_CONTROL = exports.DICTATION_CONTROL = exports.READ_ACTIVE = exports.SPEECH_ACTIVE = exports.PLUGIN_ID = void 0;
exports.PLUGIN_ID = 'speechio';
exports.SPEECH_ACTIVE = 'speech-input-active';
exports.READ_ACTIVE = 'speech-output-active';
exports.DICTATION_CONTROL = 'dictation-ctrl';
exports.READ_CONTROL = 'read-ctrl';
exports.SPEECH_IO_MANAGER_ID = 'mmirf/speechioManager';
exports.SPEECH_IO_ENGINE_ID = 'mmirf/speechioEngine';
exports.SPEECH_IO_STATES_ID = 'mmirf/state/speechio';
exports.SPEECH_IO_INPUT_ID = 'mmirf/speechioInput';
exports.SPEECH_IO_INPUT_ENGINE_ID = 'mmirf/speechioInput';
exports.SPEECH_IO_INPUT_STATES_ID = 'mmirf/state/speechioInput';
exports.BARGE_IN_CONFIG = 'enableBargeIn';
exports.ASR_ENGINE_CONFIG = 'asrEngine';
exports.TTS_ENGINE_CONFIG = 'ttsEngine';
exports.TTS_DEFAULT_OPTIONS_CONFIG = 'ttsDefaultOptions';
exports.CANCEL_ON_NEW_PROMPT_CONFIG = 'cancelOnNewPrompt';
//# sourceMappingURL=consts.js.map