export declare const PLUGIN_ID: string;
export declare const SPEECH_ACTIVE: string;
export declare const READ_ACTIVE: string;
export declare const DICTATION_CONTROL: string;
export declare const READ_CONTROL: string;
export declare const SPEECH_IO_MANAGER_ID = "mmirf/speechioManager";
export declare const SPEECH_IO_ENGINE_ID = "mmirf/speechioEngine";
export declare const SPEECH_IO_STATES_ID = "mmirf/state/speechio";
export declare const SPEECH_IO_INPUT_ID = "mmirf/speechioInput";
export declare const SPEECH_IO_INPUT_ENGINE_ID = "mmirf/speechioInput";
export declare const SPEECH_IO_INPUT_STATES_ID = "mmirf/state/speechioInput";
export declare const BARGE_IN_CONFIG = "enableBargeIn";
export declare const ASR_ENGINE_CONFIG = "asrEngine";
export declare const TTS_ENGINE_CONFIG = "ttsEngine";
export declare const TTS_DEFAULT_OPTIONS_CONFIG = "ttsDefaultOptions";
export declare const CANCEL_ON_NEW_PROMPT_CONFIG = "cancelOnNewPrompt";
